### ISSUE TITLE
Additional block information

### ISSUE THREAD

**Issue by Luphia** [BOLT-Protocol/TideWallet-Backend-Parser#8]
- Block Hash
- Timestamp
- Miner
- Difficulty
- Number of Transactions
- Merkle Root
- Size
- Transaction Volume
- Gas Used
- Block Reward
- Block Fee
- Extra Data

**Comment by Waiting4Ever** [comment]
- [ ] Block Hash
- [ ] Timestamp
- [ ] Miner
- [ ] Difficulty
- [ ] Number of Transactions
- [ ] Merkle Root
- [ ] Size
- [ ] Transaction Volume
- [ ] Gas Used
- [ ] Block Reward
- [ ] Block Fee
- [ ] Extra Data

**Comment by Luphia** [comment]
釋出版本：v1.0.0
